### ISSUE TITLE
missing files using Docker deployment

### ISSUE THREAD

**Issue by burndown** [pingfury108/book2tts#1]
Hi:
missing files when i try to access the book2tts using docker 

137 static files copied to '/app/src/web/staticfiles'.
Starting application...
[2025-05-14 05:30:09 +0000] [1] [INFO] Starting gunicorn 23.0.0
[2025-05-14 05:30:09 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2025-05-14 05:30:09 +0000] [1] [INFO] Using worker: sync
[2025-05-14 05:30:09 +0000] [24] [INFO] Booting worker with pid: 24
**Not Found: /static/css/dist/styles.css
Not Found: /static/htmx.min.js
Not Found: /static/jquery.min.js
Not Found: /static/django-browser-reload/reload-listener.js**

**Comment by pingfury108** [comment]
Sorry, no sample files for docker deployment are provided
When deploying docker, you need the cooperation of web server (nginx or caddy)
This is my docker-compose when deploying

docker-compose.yaml
```
services:
  book2tts:
    image: ghcr.io/pingfury108/book2tts:latest
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env
    environment:
      DJANGO_DEBUG: False
      DB_NAME: /app/data/db.sqlite3
      MEDIA_ROOT: /app/data/media
      STATIC_ROOT: /app/data/static
      CSRF_TRUSTED_ORIGINS: https://b2t.pingfury.top
  caddy:
    image: docker.pingfury.top/caddy:latest
    ports:
      - "4002:8000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/b2t_data
```

Caddyfile
```
:8000 {
    log {
        format console
        output stdout
    }

    handle /static/* {
        root * /b2t_data/
        file_server
    }

    handle /media/* {
        root * /b2t_data/
        file_server
    }

    handle /* {
        reverse_proxy book2tts:8000
    }
}
```

.env
```
TEXT_PROVIDER=deepseek

VOLCENGINE_API_KEY=bcecb6
VOLCENGINE_OCR_MODEL=ep-202
#VOLCENGINE_TEXT_MODEL=ep-20

DEEPSEEK_API_KEY=sk-631
DEEPSEEK_TEXT_MODEL=deepseek-chat
```
**deepseek is used here to automatically arrange the content**
